<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class TempatSeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');

        $tempat = [
            // ── WISATA ──────────────────────────────────────────────
            [
                'nama_tempat' => 'Pantai Taman Ria',
                'kategori'    => 'wisata',
                'deskripsi'   => 'Pantai ikonik Kota Palu dengan pemandangan Teluk Palu yang indah. Cocok untuk bersantai, menikmati sunset, dan spot foto kekinian di tepi pantai berpasir.',
                'alamat'      => 'Jl. Taman Ria, Palu Barat, Kota Palu',
                'foto_utama'  => null,
                'rating_avg'  => 4.5,
                'jam_buka'    => '07.00 - 18.00',
                'maps_link'   => 'https://maps.google.com/?q=Pantai+Taman+Ria+Palu',
                'status'      => 'aktif',
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'nama_tempat' => 'Jembatan Palu IV',
                'kategori'    => 'wisata',
                'deskripsi'   => 'Jembatan ikonik di pusat Kota Palu yang menjadi simbol kebangkitan pasca gempa 2018. Menjadi spot foto favorit warga dan wisatawan terutama di malam hari.',
                'alamat'      => 'Jl. Soekarno-Hatta, Palu Barat, Kota Palu',
                'foto_utama'  => null,
                'rating_avg'  => 4.6,
                'jam_buka'    => '24 jam',
                'maps_link'   => 'https://maps.google.com/?q=Jembatan+Palu+IV',
                'status'      => 'aktif',
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'nama_tempat' => 'Monumen Nosarara Nosabatutu',
                'kategori'    => 'wisata',
                'deskripsi'   => 'Monumen persatuan di Bukit Jabal Nur Kota Palu. Menawarkan panorama kota Palu dari ketinggian yang sangat memukau, terutama saat matahari terbit dan terbenam.',
                'alamat'      => 'Bukit Jabal Nur, Palu Selatan, Kota Palu',
                'foto_utama'  => null,
                'rating_avg'  => 4.7,
                'jam_buka'    => 'Setiap hari: 06.00 - 18.00',
                'maps_link'   => 'https://maps.google.com/?q=Monumen+Nosarara+Nosabatutu+Palu',
                'status'      => 'aktif',
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'nama_tempat' => 'Danau Poso',
                'kategori'    => 'wisata',
                'deskripsi'   => 'Salah satu danau terdalam di Indonesia dengan air berwarna biru kehijauan yang jernih. Cocok untuk berenang, snorkeling, dan menikmati suasana alam yang tenang.',
                'alamat'      => 'Tentena, Kabupaten Poso, Sulawesi Tengah',
                'foto_utama'  => null,
                'rating_avg'  => 4.8,
                'jam_buka'    => '08.00 - 17.00',
                'maps_link'   => 'https://maps.google.com/?q=Danau+Poso',
                'status'      => 'aktif',
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'nama_tempat' => 'Museum Sulawesi Tengah',
                'kategori'    => 'wisata',
                'deskripsi'   => 'Museum yang menyimpan koleksi benda bersejarah dan artefak budaya Sulawesi Tengah, termasuk pakaian adat, senjata tradisional, dan peninggalan megalitik.',
                'alamat'      => 'Jl. Kemiri No. 23, Palu Timur, Kota Palu',
                'foto_utama'  => null,
                'rating_avg'  => 4.2,
                'jam_buka'    => 'Senin - Jumat: 08.00 - 15.00',
                'maps_link'   => 'https://maps.google.com/?q=Museum+Sulawesi+Tengah',
                'status'      => 'aktif',
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            // ── CAFE ────────────────────────────────────────────────
            [
                'nama_tempat' => 'Kopi Palu Kita',
                'kategori'    => 'cafe',
                'deskripsi'   => 'Kedai kopi lokal dengan biji kopi pilihan dari Sulawesi Tengah. Suasana cozy dan instagramable, cocok untuk nongkrong maupun meeting santai.',
                'alamat'      => 'Jl. Juanda No. 12, Palu Timur, Kota Palu',
                'foto_utama'  => null,
                'rating_avg'  => 4.8,
                'jam_buka'    => '08.00 - 22.00',
                'maps_link'   => 'https://maps.google.com/?q=Kopi+Palu+Kita',
                'status'      => 'aktif',
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'nama_tempat' => 'Warung Kopi Tobelo',
                'kategori'    => 'cafe',
                'deskripsi'   => 'Tempat ngopi santai legendaris di Palu dengan menu sederhana dan harga ramah di kantong. Selalu ramai mahasiswa hingga larut malam.',
                'alamat'      => 'Jl. Patimura, Palu Selatan, Kota Palu',
                'foto_utama'  => null,
                'rating_avg'  => 4.3,
                'jam_buka'    => '07.00 - 24.00',
                'maps_link'   => 'https://maps.google.com/?q=Warung+Kopi+Tobelo+Palu',
                'status'      => 'aktif',
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'nama_tempat' => 'Rumah Kapurung Palu',
                'kategori'    => 'cafe',
                'deskripsi'   => 'Restoran khas masakan Sulawesi Tengah yang menyajikan kapurung, ikan bakar, dan berbagai kuliner lokal autentik dalam suasana rumahan yang hangat.',
                'alamat'      => 'Jl. Diponegoro No. 5, Palu Barat, Kota Palu',
                'foto_utama'  => null,
                'rating_avg'  => 4.6,
                'jam_buka'    => 'Setiap hari: 10.00 - 21.00',
                'maps_link'   => 'https://maps.google.com/?q=Rumah+Kapurung+Palu',
                'status'      => 'aktif',
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'nama_tempat' => 'Om Ded Pisang Keju',
                'kategori'    => 'cafe',
                'deskripsi'   => 'Kedai pisang keju kekinian yang hits di Palu. Varian rasa beragam dan topping melimpah, cocok untuk camilan sore sambil nongkrong bersama teman.',
                'alamat'      => 'Jl. Wahid Hasyim, Palu Timur, Kota Palu',
                'foto_utama'  => null,
                'rating_avg'  => 4.4,
                'jam_buka'    => '10.00 - 21.00',
                'maps_link'   => 'https://maps.google.com/?q=Om+Ded+Pisang+Keju+Palu',
                'status'      => 'aktif',
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            // ── HIDDEN GEM ──────────────────────────────────────────
            [
                'nama_tempat' => 'Air Terjun Kalukubula',
                'kategori'    => 'hidden_gem',
                'deskripsi'   => 'Air terjun tersembunyi di Sigi dengan air alami yang sangat jernih dan sejuk. Lokasinya yang jauh dari keramaian membuat tempat ini terasa sangat damai.',
                'alamat'      => 'Desa Kalukubula, Kabupaten Sigi, Sulawesi Tengah',
                'foto_utama'  => null,
                'rating_avg'  => 4.7,
                'jam_buka'    => '06.00 - 16.00',
                'maps_link'   => 'https://maps.google.com/?q=Air+Terjun+Kalukubula',
                'status'      => 'aktif',
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'nama_tempat' => 'Puncak Selena',
                'kategori'    => 'hidden_gem',
                'deskripsi'   => 'Bukit dengan panorama sunrise terbaik di Kota Palu. Dari puncaknya terlihat seluruh kota hingga Teluk Palu. Belum banyak wisatawan yang mengetahui lokasi ini.',
                'alamat'      => 'Palu Selatan, Kota Palu, Sulawesi Tengah',
                'foto_utama'  => null,
                'rating_avg'  => 4.6,
                'jam_buka'    => '05.00 - 10.00',
                'maps_link'   => 'https://maps.google.com/?q=Puncak+Selena+Palu',
                'status'      => 'aktif',
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'nama_tempat' => 'Pantai Mbela-Mbela',
                'kategori'    => 'hidden_gem',
                'deskripsi'   => 'Pantai tersembunyi di pinggiran Kota Palu dengan pasir putih dan air biru yang masih sangat bersih. Cocok untuk piknik keluarga dan snorkeling.',
                'alamat'      => 'Tawaeli, Palu Utara, Kota Palu',
                'foto_utama'  => null,
                'rating_avg'  => 4.5,
                'jam_buka'    => '06.00 - 18.00',
                'maps_link'   => 'https://maps.google.com/?q=Pantai+Mbela+Mbela+Palu',
                'status'      => 'aktif',
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
        ];

        $this->db->table('tempat')->insertBatch($tempat);
    }
}
